--tabel menu add  field remark by zyh20130806
alter table menu  ADD (remark varchar(100));
CREATE TABLE `organization` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(30) NULL DEFAULT NULL,
	`addr` VARCHAR(50) NULL DEFAULT NULL,
	`picid` BIGINT(20) NULL DEFAULT NULL,
	`sortnum` SMALLINT(6) NULL DEFAULT NULL,
	`remark` VARCHAR(100) NULL DEFAULT NULL,
	`num` VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
);
CREATE TABLE `partment` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NULL DEFAULT NULL,
	`remark` VARCHAR(250) NULL DEFAULT NULL,
	`picid` BIGINT(20) NULL DEFAULT NULL,
	`orgid` BIGINT(20) NULL DEFAULT NULL,
	`pid` BIGINT(10) NULL DEFAULT NULL COMMENT '父级部门id',
	`num` VARCHAR(20) NULL DEFAULT NULL,
	PRIMARY KEY (`id`)
)COLLATE='utf8_general_ci' ENGINE=InnoDB;